#!/bin/bash
#simple bash script for compiling java files into class files
#compiles all .java files within the root directory into class files within classes/
java --version
echo Starting Java compile...
javac *.java
echo Complete.